apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
  namespace: argocd
spec:
  replicas: 1
  strategy:
    canary:
      # analysis:
      #   templates:
      #     - templateName: success-rate
      canaryService: "app-canary"
      stableService: "app"
      trafficRouting:
        istio:
          virtualService:
            name: virtual-service
            routes:
              - app
      # steps:
      #   # - setCanaryScale:
      #   - setWeight: 10
      #   - pause: { duration: 10 }
      #   - setWeight: 20
      #   - pause: { duration: 20 }
      #   - setWeight: 40
      #   - pause: { duration: 20 }
      #   - setWeight: 60
      #   - pause: { duration: 20 }
      #   - setWeight: 80
      #   - pause: { duration: 20 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-v1
