environments:
  dev:
    values:
      - clusterName: agent-territory-management
  prod:
    values:
      - clusterName: agent-territory-management
---
repositories:
  - name: standard-app
    url: https://julinux-io.github.io/standard-app/

helmDefaults:
  createNamespace: true

releases:
  - name: web
    chart: standard-app/standard-app
    namespace: develop
    values:
      - ./common/web.values.yaml
      - ./dev/web.values.yaml
    secrets:
      - ./web-secrets.sops.yaml

  # - name: graphql
  #   chart: standard-app/standard-app
  #   namespace: develop
  #   values:
  #     - ./common/graphql.values.yaml
  #     - ./{{ .Environment.Name }}/graphql.values.yaml
  #   secrets:
  #     - ./graphql-secrets.sops.yaml

  # - name: varnish
  #   chart: standard-app/standard-app
  #   namespace: develop
  #   values:
  #     - ./common/varnish.values.yaml
  #     - ./{{ .Environment.Name }}/varnish.values.yaml

  # - name: tiles
  #   chart: standard-app/standard-app
  #   namespace: develop
  #   values:
  #     - ./common/tiles.values.yaml
