environments:
  dev:
    values:
      - clusterName: argocd-conf
---
repositories:
  - name: opsmx
    url: https://helmcharts.opsmx.com/

  - name: argo
    url: https://argoproj.github.io/argo-helm

  - name: cert-manager
    url: https://charts.jetstack.io

  - name: nginx
    url: https://helm.nginx.com/stable

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  createNamespace: true

releases:
  - name: spinnaker
    namespace: spinnaker
    labels:
      app: spinnaker
    chart: opsmx/spinnaker
    version: "2.2.7"

  - name: argocd
    namespace: argocd
    labels:
      app: argocd
    chart: argo/argo-cd
    version: "~5.34.6"

  - name: argocd-rollouts
    namespace: argocd
    labels:
      app: argocd
    chart: argo/argo-rollouts
    version: "2.32.0"
    set:
      - name: dashboard.enabled
        value: true

  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    version: 1.12.2
    hooks:
      - events: ["prepare"]
        command: "./scripts/cert-manager-crds.sh"
    values:
      - serviceAccount:
          annotations:
            {
              eks.amazonaws.com/role-arn: arn:aws:iam::916001899522:role/cert-manager,
            }

  - name: nginx-ingress
    namespace: nginx-ingress
    labels:
      app: nginx-ingress
    chart: nginx/nginx-ingress
    version: "0.18.1"
    set:
      - name: controller.metrics.enabled
        value: true
      - name: controller.podAnnotations
        values: ["prometheus.io/scrape: true", "prometheus.io/port: 10254"]
      - name: controller.metrics.service.annotations
        values: ["prometheus.io/scrape: true", "prometheus.io/port: 10254"]

  - name: prometheus
    namespace: monitoring
    labels:
      app: prometheus
    chart: prometheus-community/prometheus
    version: "24.5.0"
    values:
      - ./values/prometheus.values.yaml

  - name: grafana
    namespace: monitoring
    chart: bitnami/grafana
    version: 9.1.1
