apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
spec:
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
        args:
          - name: service-name
            value: app-blue.default.svc.cluster.local
      canaryService: "app-blue"
      stableService: "app-green"
      trafficRouting:
        nginx:
          stableIngress: "app-green"
          # annotationPrefix: "nginx.ingress.kubernetes.io"
          # additionalIngressAnnotations:
          #   canary: "true"
          #   canary-weight: "25"
      steps:
        - setWeight: 10
        - pause: { duration: 20 }
        - setWeight: 20
        - pause: { duration: 30 }
        - setWeight: 40
        - pause: { duration: 30 }
        - setWeight: 60
        - pause: { duration: 30 }
        - setWeight: 80
        - pause: { duration: 30 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      v1: green
      v2: blue
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rollout
