apiVersion: v1
kind: Service
metadata:
  name: app-green
  labels:
    release: web
    role: green
  annotations:
    # kubectl.kubernetes.io/last-applied-configuration: |
    #   {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"9090","prometheus.io/scrape":"true"},"name":"prometheus-service","namespace":"monitoring"},"spec":{"ports":[{"nodePort":30000,"port":80,"targetPort":9090}],"selector":{"app":"prometheus-server"},"type":"NodePort"}}
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
spec:
  selector:
    v1: green
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-app-blue-canary
  labels:
    release: web
    role: blue
spec:
  selector:
    v2: blue
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
