image:
  repository: nhds/agent-territory-management
  tag: "4.0.0"
  imagePullSecrets:
    enabled: true

http:
  app:
    args:
      - npm
      - run
      - staging
    envVars:
      REACT_APP_MAP_TILE_HOST: https://devvarnish.maptool.neighborhoods.com/
      REACT_APP_GQL_HOST_HTTP: https://devgraphql.maptool.neighborhoods.com/v1/graphql
      REACT_APP_GQL_HOST_WS: wss://devgraphql.maptool.neighborhoods.com/v1/graphql

secret:
  secretName: web
  secretType: "kubernetes.io/dockerconfigjson"
  imagePullSecrets:
    enabled: true

ingress:
  auth: true
  class: alb
  enabled: true
  host: dev.maptool.neighborhoods.com
  pathType: ""
  path: ""

  extraAnnotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:272157948465:certificate/1069f35d-9986-4b61-83d3-53a39caa7fa7
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ingress
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-30a68c54
    alb.ingress.kubernetes.io/subnets: subnet-0b58187c,subnet-38593d61

service:
  name: agent-territory-management
  type: NodePort
