apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: defaults
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: virtual-service
        number: 443
        protocol: HTTPS
  #   tls:
  #     credentialName: httpbin-ingress-cert
  #     mode: SIMPLE
  # - hosts:
  #   - canary.33test.dev-sandbox.fpcomplete.com
  # port:
  #   name: http-httpbin
  #   number: 80
  #   protocol: HTTP
  # tls:
  #   httpsRedirect: true
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service
  namespace: default
spec:
  gateways:
    - ingress-gateway
  hosts:
    - canary.33test.dev-sandbox.fpcomplete.com
  http:
    - route:
        - destination:
            host: httpbin.canary.svc.cluster.local
            port:
              number: 8000
            subset: v1
          weight: 80
        - destination:
            host: httpbin.canary.svc.cluster.local
            port:
              number: 8001
            subset: v2
          weight: 20
---

