apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
spec:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: "10"
        - setWeight: 50
        - pause:
            duration: "20"
      # canaryService: nginx-canary.canary.svc.cluster.local
      # stableService: nginx-prod.default.svc.cluster.local
      trafficRouting:
        istio:
          virtualService:
            name: istio-vs
            routes:
              - canary
