apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
  namespace: default
spec:
  replicas: 10
  strategy:
    blueGreen:
      activeService: prod
      previewService: prod-1
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
