apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout
  namespace: argocd
spec:
  project: default
  source:
    path: .
    repoURL: "https://github.com/xlp67/rollouts.git"
    targetRevision: strategy-deploy
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
