apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  project: default
  source:
    repoURL: https://github.com/xlp67/rollouts.git
    targetRevision: strategy-deploy
    path: app/v1/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
