apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/xlp67/rollouts.git
        revision: "strategy-deploy"
        directories:
          # - path: "app/v1/build"
          - path: "app/v1/manifests"
          - path: "app/v2/manifests"
  template:
    metadata:
      name: app
    spec:
      project: default
      source:
        repoURL: https://github.com/xlp67/rollouts.git
        targetRevision: strategy-deploy
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
