apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  labels:
    name: prometheus
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'app'
        scrape_interval: 5s
        static_configs:
          - targets: ['app.default.svc:8181']
        metrics_path: /metrics
