app:
  image:
    repository: "hasura/graphql-engine"
    registry: registry.hub.docker.com/
    tag: latest
  imagePullSecrets:
    enabled: false
  logRoot: "/var/log"
  envVars:
    HASURA_GRAPHQL_DEV_MODE: "false"
    HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
    HASURA_GRAPHQL_SERVER_PORT: 80
  envVarsRaw:
    - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: hasura
          key: metadata-db-url
    - name: HASURA_GRAPHQL_ADMIN_SECRET
      valueFrom:
        secretKeyRef:
          name: hasura
          key: admin-secret
    - name: PG_DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: hasura
          key: pg-db-url

appName: agent-territory-management-graphql

http:
  app:
    ports:
      - name: http
        containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 2048Mi

  # priorityClassName: internal-frontend-important

nginx:
  enabled: false

service:
  name: graphql
  targetPort: http
  type: NodePort
