app:
  image:
    repository: "eeacms/varnish"
    registry: registry.hub.docker.com/
    tag: latest
  imagePullSecrets:
    enabled: false
  logRoot: "/var/log"
  envVars:
    BACKENDS: "tiles"
  envVarsRaw:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: hasura
          key: pg-db-url

appName: agent-territory-management-varnish

http:
  app:
    ports:
      - name: http
        containerPort: 6081
    readinessProbe:
      tcpSocket:
        port: 6081
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 2048Mi

  # priorityClassName: internal-frontend-important

nginx:
  enabled: false

service:
  name: varnish
  targetPort: http
  type: NodePort
