apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  labels:
    app: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        version: "2.0"
      annotations:
        prometheus.io/scrape: "true"
        proometheus.io/port: "8181"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: metrics
          image: xlp67/girus2
          resources: {}
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
